# Generated by Django 4.2.4 on 2023-08-26 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConverseNetUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=50)),
                ("Date_Of_Birth", models.DateField(null=True)),
                (
                    "user_ID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendsThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "friends_User_id_Person1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person1",
                        to="Home.conversenetuser",
                    ),
                ),
                (
                    "friends_User_id_Person2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.conversenetuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.TextField(max_length=1000000)),
                (
                    "friends_User_id_Person1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person12",
                        to="Home.conversenetuser",
                    ),
                ),
                (
                    "friends_User_id_Person2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.conversenetuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(max_length=10000000)),
                (
                    "converseNet_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.conversenetuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendsThreadMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=1000000)),
                (
                    "friends_Chat_Time",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "sender_Id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.conversenetuser",
                    ),
                ),
                (
                    "thread_Id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Thread",
                        to="Home.friendsthread",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("note", models.TextField(default=None, max_length=10000000)),
                (
                    "time",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "converseNet_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.conversenetuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bot_Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "converseNet_user_Message",
                    models.TextField(default=None, max_length=10000000),
                ),
                ("reply_Message", models.TextField(max_length=10000000)),
                (
                    "message_Time",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "converseNet_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.conversenetuser",
                    ),
                ),
            ],
        ),
    ]
